myapp/urls.py
from django.urls import path
from myapp import views
from myapp.views import Index, Detail

app_name = 'myapp'

urlpatterns = [#path(r'', views.index, name='index'),
               path(r'', Index.as_view(), name='index'),
               path(r'about/', views.about, name='about'),
               #path(r'<int:topic_id>/', views.detail, name='detail'),
               path(r'<int:topic_id>/', Detail.as_view(), name='detail'),
               path(r'findcourses/', views.findcourses, name='findcourses'),
               path(r'place_order/', views.place_order, name='place_order'),
               path(r'review/', views.review, name='review'),
               path(r'login/', views.user_login, name='user_login'),
               path(r'logout/', views.user_logout, name='user_logout'),
               path(r'myaccount/', views.myaccount, name='myaccount'),
               path(r'register/', views.register, name='register'),
               path(r'myorder/', views.myorder, name='myorder'),               
               ]

mysiteF20/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
    path(r'myapp/reset_password/', 
    auth_views.PasswordResetView.as_view(template_name="myapp/accounts/password_reset.html"), name="reset_password"),
    path(r'myapp/reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(template_name="myapp/accounts/password_reset_sent.html"), name="password_reset_done"),
    path(r'myapp/reset/<uidb64>/<token>/', 
    auth_views.PasswordResetConfirmView.as_view(template_name="myapp/accounts/password_reset_form.html"), name="password_reset_confirm"),
    path(r'myapp/reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name="myapp/accounts/password_reset_done.html"), name="password_reset_complete")
]

myapp/forms.py
from django import forms
from datetime import datetime
from myapp.models import Order, Review, Student, Course


class SearchForm(forms.Form):
    LENGTH_CHOICES = [
        (8, '8 Weeks'),
        (10, '10 Weeks'),
        (12, '12 Weeks'),
        (14, '14 Weeks'),
    ]
    name = forms.CharField(max_length=100, required=False, label='Student Name')
    length = forms.TypedChoiceField(widget=forms.RadioSelect, choices=LENGTH_CHOICES, coerce=int,
                                    label='Preferred course duration:', required=False, empty_value=0)
    max_price = forms.IntegerField(label='Maximum Price', min_value=0)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['courses', 'student', 'order_status']
        widgets = {'courses': forms.CheckboxSelectMultiple(), 'order_type': forms.RadioSelect}
        labels = {'student': u'Student Name', }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = {'reviewer', 'course', 'rating', 'comments'}
        widgets = {'courses': forms.RadioSelect()}
        labels = {'reviewer': u'Please enter a valid email', 'rating': u'Rating: An integer between 1 (worst) and 5 (best)'}


class StudentRegisterForm(forms.ModelForm):
    class Meta:
        LVL_CHOICES = [('HS', 'High School'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('ND', 'No Degree')]
        model = Student
        fields = {'username', 'email', 'password', 'interested_in', 'first_name', 'last_name','photo'}
        widgets = {'level': forms.TypedChoiceField(widget=forms.RadioSelect, choices=LVL_CHOICES, empty_value='HS'),
                   'address': forms.CharField(max_length=300, required=False),
                   'province': forms.CharField(max_length=2, empty_value='ON'),
                   'registered_courses': forms.ModelMultipleChoiceField(required=False, queryset=Course.objects.all())}

    LVL_CHOICES = [('HS', 'High School'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('ND', 'No Degree')]
    level = forms.TypedChoiceField(label='Level', widget=forms.RadioSelect, choices=LVL_CHOICES, empty_value='HS')
    address = forms.CharField(label='Address', max_length=300, required=False)
    province = forms.CharField(label='Province', max_length=2, empty_value='ON')
    registered_courses = forms.ModelMultipleChoiceField(label='Registered Courses', required=False,
                                                        queryset=Course.objects.all())
    field_order = ['username', 'email', 'password','interested_in', 'first_name', 'last_name','level', 'address','province','registered_courses','photo']

myapp/views.py
from django.core.checks import messages
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Topic, Course, Student, Order, Review, User
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from datetime import datetime
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect


# Create your views here.
class Index(View):
     def get(self, request, *args, **kwargs):
        if request.session.get('last_login'):
            self.top_list = Topic.objects.all().order_by('id')[:10]
            self.student_name = request.user.get_username()
            return render(request, 'myapp/index.html', {'top_list': self.top_list, 'student_name': self.student_name})
        else:
            http_response = HttpResponse()
            http_response.write('<html> Your last login was more than one hour ago. </html>')
            return http_response



# def index(request):
#     if request.session.get('last_login'):
#         top_list = Topic.objects.all().order_by('id')[:10]
#         student_name = request.user.get_username()
#         return render(request, 'myapp/index.html', {'top_list': top_list, 'student_name': student_name})
#     else:
#         http_response = HttpResponse()
#         http_response.write('<html> Your last login was more than one hour ago. </html>')
#         return http_response


def about(request):
    student_name = request.user.get_username()
    if request.session.get('about_visits'):
        request.session['about_visits'] += 1
        request.session.set_expiry(300)
        about_visits = request.session['about_visits']
    else:
        request.session['about_visits'] = 1
        request.session.set_expiry(300)
        about_visits = request.session['about_visits']
    return render(request, 'myapp/about.html', {'student_name': student_name, 'about_visits': about_visits})

class Detail(View):
     def get(self, request, *args, **kwargs):
        self.student_name = request.user.get_username()
        self.topic_local = get_object_or_404(Topic, pk=kwargs['topic_id'])
        self.courses = Course.objects.filter(topic=kwargs['topic_id'])
        self.topic_name = self.topic_local.name.upper()
        self.topic_length = str(self.topic_local.length) + ' weeks'
        return render(request, 'myapp/detail.html',
                    {'topic_name': self.topic_name, 'topic_length': self.topic_length, 'courses': self.courses, 'student_name': self.student_name})


# def detail(request, topic_id):
#     student_name = request.user.get_username()
#     topic_local = get_object_or_404(Topic, pk=topic_id)
#     courses = Course.objects.filter(topic=topic_id)
#     topic_name = topic_local.name.upper()
#     topic_length = str(topic_local.length) + ' weeks'
#     return render(request, 'myapp/detail.html',
#                   {'topic_name': topic_name, 'topic_length': topic_length, 'courses': courses, 'student_name': student_name})


def findcourses(request):
    # breakpoint()
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            length = form.cleaned_data['length']
            max_price = form.cleaned_data['max_price']
            if length != 0:
                topics = Topic.objects.filter(length=length)
                course_list = []
                for top in topics:
                    if top.courses.filter(price__lte=max_price).count() != 0:
                        course_list.append((top, list(top.courses.filter(price__lte=max_price))))
                return render(request, 'myapp/results.html',
                              {'course_list': course_list, 'name': name, 'length': length})
            else:
                topics = Topic.objects.all()
                course_list = []
                topics.distinct('name')
                for top in topics:
                    if top.courses.filter(price__lte=max_price).count() != 0:
                        course_list.append((top, list(top.courses.filter(price__lte=max_price))))
                return render(request, 'myapp/results.html',
                              {'course_list': course_list, 'name': name, 'length': length})
        else:
            return HttpResponse('Invalid data')
    else:
        form = SearchForm()
        student_name = request.user.get_username()
        return render(request, 'myapp/findcourses.html', {'form': form, 'student_name': student_name})


def place_order(request):
    student_name = request.user.get_username()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            courses = form.cleaned_data['courses']
            order = form.save(commit=True)
            student = order.student
            status = order.order_status
            order.save()
            if status == 1:
                for c in order.courses.all():
                    student.registered_courses.add(c)
            return render(request, 'myapp/order_response.html',
                          {'courses': courses, 'order': order, 'student_name': student_name})
        else:
            return render(request, 'myapp/place_order.html', {'form': form, 'student_name': student_name})
    else:
        form = OrderForm()
        return render(request, 'myapp/place_order.html', {'form': form, 'student_name': student_name})
@login_required
def review(request):
    student_name = request.user.get_username()
    student = Student.objects.get(username=student_name)
    student_type = student.level
    if(student_type == 'UG' or student_type =='PG'):
        if request.method == 'POST':
            form = ReviewForm(request.POST)
            if form.is_valid():
                rating = form.cleaned_data['rating']
                if 5 >= rating >= 1:
                    course = form.cleaned_data['course']
                    c = Course.objects.get(title=course.title)
                    c.num_reviews += 1
                    c.save()
                    f = form.save()
                    f.save()
                    top_list = Topic.objects.all().order_by('id')[:10]
                    return render(request, 'myapp/index.html', {'top_list': top_list, 'student_name': student_name})
                else:
                    form = ReviewForm()
                    message = 'You must enter a rating between 1 and 5!'
                    return render(request, 'myapp/review.html',
                                {'form': form, 'student_name': student_name, 'message': message})
            else:
                form = ReviewForm()
                return render(request, 'myapp/review.html', {'form': form, 'student_name': student_name})
        else:
            form = ReviewForm()
            return render(request, 'myapp/review.html', {'form': form, 'student_name': student_name})
    else:
        return render(request, 'myapp/error.html',{'msg':"User not authorized to review. Must be UG or PG student."})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['last_login'] = str(datetime.today()) + str(datetime.now())
                request.session.set_expiry(3600)
                return HttpResponseRedirect(reverse('myapp:myaccount'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return render(request, 'myapp/error.html', {'msg':"Invalid Login detail."})
    else:
        try:
            logout(request,request.user)
        except:
            return render(request, 'myapp/login.html')
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    try:
        logout(request)
        return render(request, 'myapp/logout.html',{'message':"Logout Successful."})
    except:
        return render(request,'myapp/logout.html',{'message': "Not Logged in."})


@login_required
def myaccount(request):
    user_name = request.user.get_username()
    student = Student.objects.get(username=user_name)
    if student:
        firstname = student.first_name
        lastname = student.last_name
        name = firstname + " " + lastname
        interested_in = student.interested_in
        registered_courses = student.registered_courses
        topic_list = []
        topic_list.append(type(interested_in))
        topic_list.append(interested_in)
        # for topic in interested_in:
        #     topic_list.append(topic)
        course_list = []
        course_list.append(type(registered_courses))
        course_list.append(registered_courses)
        # for course in registered_courses:
        #     course_list.append(course)
        return render(request, 'myapp/myaccount.html',
                      {'student_name': name, 'firstname': firstname, 'lastname': lastname, 'topic_list': topic_list, 'course_list': course_list})
    else:
        return render(request, 'myapp/myaccount.html', {'message': 'You are not a registered student!'})

@login_required
def myorder(request):
    user_name = request.user.get_username()
    try:
        st = Student.objects.get(username=user_name)
        firstname = st.first_name 
        lastname = st.last_name
        if st:
            orders = Order.objects.filter(student = st.id)
            if orders:
                return render(request, 'myapp/myorder.html', {'first_name': firstname, 'last_name': lastname , 'orders': orders})
            else:
                return render(request, 'myapp/myorder.html', {'first_name': firstname, 'last_name': lastname , 'orders': None})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block title %}
    eLearning - APP About page
{% endblock %}

{% block body_block %}
    <p>This is an E-learning Website! Search our Topics to find all available Courses.</p>
    <p> about_visits: {{ about_visits }}</p>
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>This is an E-learning Website! Search our Topics to find all available Courses.</p>
<p><a href="{% url 'myapp:index' %}">Index page</a></p>
<p><a href="/myapp/">Index page</a></p>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"
    />
    <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>
<div>
    <h1>{% block myhdg %}Hello {{ student_name }}{% endblock %}</h1>
    {% block body_block %}*** {% endblock %}
</div>
<hr/>
<div>
    <ul>
        <li class="hbar1"><a href="/myapp/about/">Find out about this site</a></li>
        <li class="hbar1"><a href="{% url 'myapp:index' %}">Click here to return to main page</a></li>
        <li class="hbar1"><a href="{% url 'myapp:findcourses' %}">Search of a course</a></li>
        <li class="hbar1"><a href="{% url 'myapp:place_order' %}">Place an order</a></li>
        <li class="hbar1"><a href="{% url 'myapp:review' %}">Review</a></li>
        
        {% if student_name %}
            <li class="hbar1"><a href="{% url 'myapp:myorder' %}">My Order</a></li>
            <li class="hbar1"><a href="{% url 'myapp:myaccount' %}">My Account</a></li>
            <li class="hbar1"><a href="{% url 'myapp:user_logout' %}">Logout</a></li>
        {% else %}
        <li class="hbar1"><a href="{% url 'myapp:register' %}">Register</a></li>
        <li class="hbar1"><a href="{% url 'myapp:user_login' %}">Login</a></li>
        {% endif %}
    </ul>
</div>
</body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <p>{{ topic_name }}</p>
    <p>{{ topic_length }}</p>
    <ol>
        {% for course in courses %}
            <li> {{ course.title }} </li>
        {% endfor %}
    </ol>
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>{{ topic_name }}</p>
<p>{{ topic_length }}</p>
<ol>
    {% for course in courses %}
        <li> {{ course.title }} </li>
    {% endfor %}
</ol>
<p><a href="{% url 'myapp:index' %}">Index page</a></p>
</body>
</html>

myapp/templates/myapp/error.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <p>{{ msg }}</p>

{% endblock %}

myapp/templates/myapp/findcourses.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:findcourses' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit1" value="Find Courses"/>
    </form>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
    Hello {{student_name}}
{% endblock %}

{% block body_block %}
    {% if top_list %}
        <h2>List of Topics</h2>
        <ol>
            {% for top in top_list %}
                <li><a href={% url 'myapp:detail' top.pk %}> {{ top.name }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
{% endblock %}

myapp/templates/myapp/logout.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h2>{{ message }}</h2>
{% endblock %}

myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}

{% block body_block %}
{% if message %}
<h2>{{ message }}</h2>
{% else %}
<h2>First Name: {{ firstname }}</h2>
<h2>First Name: {{ lastname }}</h2>
<h2>Interested Topics</h2>
<ol>
    {% for topic in topic_list %}
    <li>
        {{ topic }}
    </li>
    {% endfor %}
</ol>
<h2>Registered Courses</h2>
<ol>
    {% for course in course_list %}
    <li>
        {{ course }}
    </li>
    {% endfor %}
</ol>
{% endif %}

{% endblock %}

myapp/templates/myapp/myorder.html
{% extends 'myapp/base.html' %}

{% block myhdg %}Hello {{ first_name }} {{last_name}} {% endblock %}
{% block body_block %}
{% if orders %}   
    <h2>List of Order</h2>
        <ol>
            {% for order in orders %}
                <h3>
                    Course: {{ order.total_items}}
                </h3>
                <h3>
                    Order Status: {% if order.order_status == 0 %} Cancelled {% elif order.order_status == 1 %} Confirmed {% elif order.order_status == 2 %} On Hold {% else %} Invalid Status {% endif %}
                </h3>
                <h3>
                    Order Date: {{ order.order_date }}
                </h3>
                
            {% endfor %}
        </ol>
{% else %}
    <h2> No Order found.</h2>
{% endif %}
{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block myhdg %}Hello {{ name }} {% endblock %}

{% block body_block %}
    <h2>Order: {{ order }}</h2>
    <h2>List of Courses</h2>
    <ol>
        {% for course in courses %}
            <h2>
                Title: {{ course.title }}
            </h2>
        {% endfor %}
    </ol>
{% endblock %}

myapp/templates/myapp/place_order.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:place_order' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit1" value="Place Order"/>
    </form>
{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<form action="{% url 'myapp:register' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="submit1" value="Register"/>
</form>
{% endblock %}